
[package]
name = "sparsifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.16.1"
rand = "0.8.5"
ndarray-rand = "0.15.0"
fasthash = "0.4.0"
sprs = "0.11.3"
